---
- name: Check that the /etc/kubernetes/kubelet.conf exists
  stat:
    path: /etc/kubernetes/kubelet.conf
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: kubelet_presence

- name: Join Kubernetes cluster
  command: |
    kubeadm join --discovery-token-ca-cert-hash sha256:{{hostvars[groups['k8s-control-plane'][0]].cert[0]}} --token {{hostvars[groups['k8s-control-plane'][0]].token[0]}} {{hostvars[groups['k8s-control-plane'][0]].ansible_default_ipv4.address}}:{{kubernetes_default_port}}
  when: kubelet_presence.stat.exists == False
