# gather facts from haproxy node
- hosts: kube-apiserver-haproxy[0]
  name: Gather facts from collectors
  tasks: [ ]
  
- name: Setup k8s controler main
  hosts: k8s-control-plane[0]
  become: yes
  gather_facts: yes
  strategy: linear
  roles:
    - k8s-controler-haproxy 

## TODO
# - name: Setup k8s controler others
#   hosts: k8s-control-plane[1:]
#   become: yes
#   gather_facts: yes
#   strategy: linear
#   roles:
#     - k8s-controler-join



- name: Setup k8s worker
  hosts: 
    - k8s-worker
  become: yes
  gather_facts: yes
  strategy: linear
  roles:
    - k8s-worker
