---
- name: Install HAProxy on VICE proxy
  hosts: outward-facing-proxy
  gather_facts: true
  become: yes
  roles:
    - { role: vice-haproxy-installer }

  # Vars newly added
  vars: # TODO add while running?
    tls_pem_path: /etc/ssl/certs/cyverse.run.pem    
    domain: cyverse.at
    regsub: '\.cyverse\.at$,'

  tasks:
    - name: reload haproxy
      systemd:
        daemon_reload: yes
        service: haproxy
        state: reloaded
        enabled: yes
