---
- name: Setup kubernetes yum repo
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: "0644"

- name: SELinux permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  notify:
    - Reboot and wait

- name: Install kube{let,adm,ctl}
  ansible.builtin.yum:
    name:
      - kubelet-1.26.1
      - kubeadm-1.26.1
      - kubectl-1.26.1
    state: present

- name: Copy k8s.conf
  ansible.builtin.copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: "0644"

- name: Add the dummy module and make sure it is loaded after reboots
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  with_items:
    - "br_netfilter"
    - "overlay"

# NOTE no idea what this should doing
# - name: sysctl --system
#   shell: sysctl --system
