---
- name: Install HAProxy on VICE proxy
  hosts: outward-facing-proxy
  gather_facts: true
  become: yes
  roles:
    - { role: vice-haproxy-installer, include_dev: True }

  # Vars newly added
  vars:
    tls_pem_path: /etc/ssl/certs/cyverse.run.pem
    domain: cyverse.at
    regsub: '\.cyverse\.at$,'
    include_dev: False

  tasks:
    - name: reload haproxy
      systemd:
        daemon_reload: yes
        service: haproxy
        state: reloaded
        enabled: yes
