---
- name: setup kubernetes yum repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: setenforce 0
  shell: setenforce 0
  ignore_errors: True

- name: selinux permissive mode
  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  ignore_errors: True

- name: install kubelet
  package:
    name: kubelet-1.25.5
    state: present

- name: install kubeadm
  package:
    name: kubeadm-1.25.5
    state: present

- name: install kubectl
  package:
    name: kubectl-1.25.5
    state: present

- name: copy k8s.conf
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: modprobe br_netfilter
  shell: modprobe br_netfilter
  ignore_errors: yes

- name: modprobe overlay
  shell: modprobe overlay
  ignore_errors: yes

- name: sysctl --system
  shell: sysctl --system
